### ISSUE TITLE
Nothing happened with nvcc

### ISSUE THREAD

**Issue by JonghoLee0** [NVlabs/planercnn#56]
Hi.

Thanks for sharing these great codes, and sorry for the following stupid questions. I'm new in this field.

1. After running: nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=[arch], nothing happened. I think compilation didn't succeed. What are the normal results after running this command?

2. Regarding "Models are saved under checkpoint/. ", I can't find the folder checkpoint/. Does this mean compilation failed? What do I need to do to fix these issues?

3. Can I compile this on Windows as well?

Just FYI, I used pytorch 0.4.0+CUDA 10.2+Ubuntu 18.04.5

Thanks!

**Comment by ajithvcoder** [comment]
@purmod 
1. nothing will happen after nvcc comilation you have to proceed forwars
2. You have to create checkpoints folder and unizip the pretrained models
3. Yes but u have to fix every issue you are facing
(You have to build with pytorch 0.4.0 + cuda 8.0 + ubunutu 18.04+gcc 5+
then run the evalulate.py or training with pytorch 0.4.1 .) it worked for me like that

**Comment by JonghoLee0** [comment]
@ajithvallabai 

Thanks a lot for your quick and kind response! 

1. Got it.
2. Do you mean that I have to create a folder named with 'checkpoint" by myself?
3. Can I install cuda 8.0 on Ubuntu 18.04? From the website: https://developer.nvidia.com/cuda-80-ga2-download-archive, I can download cuda 8.0 for Ubuntu 16.04 and 14.04 only.

Thanks a lot again!

**Comment by ajithvcoder** [comment]
@purmod 
2.Yes 
3.You can install cuda 8.0 on Ubuntu 18.04. ( I installed in colab it worked and we can save a lot of memory . if you want i can share the notebook to your mail id )

**Comment by purmod** [comment]
@ajithvallabai 

Thanks! My email address is purmod_at_gmail_dot_com. Actually, I'm new in colab. Can I use the notebook to run planercnn without installing anything?

**Comment by Karthikaddagadderamesh** [comment]
@ajithvallabai  Hello i am trying to setup in google colab too. I have already set up the gcc,cuda and torch and was able to compile 
nms and roi

If possible can you share your colab I wanted to know if my steps were correct and also see how to download the checkpoint in colab. I am new to ggole colab and this would be very helpful

email-id: karthikramesh94@gmail.com

**Comment by ajithvcoder** [comment]
@Karthikaddagadderamesh mailed u

**Comment by ajithvcoder** [comment]
@purmod  could you close this issue as it is resolved
